### ISSUE TITLE
Dated nodes in SARS-COV-2 tree

### ISSUE THREAD

**Issue by jeromekelleher** [nextstrain/nextclade_data#47]
Hi :wave: thanks for an amazing resource!

I would find it very useful if the node times used in the main UI could be included somewhere in the archival datasets (e.g. [here](
https://github.com/nextstrain/nextclade_data/tree/release/data/datasets/sars-cov-2/references/MN908947/versions/2022-10-27T12:00:00Z/files))

I'm using these archival datasets over the download options provided in the [main UI](https://nextstrain.org/ncov/gisaid/global/6m) for two reasons: (1) it's nice to have a stable URL to use in my scripts rather than manually downloading the data from the web browser; and (2) the UI doesn't seem to provide a JSON option any more which I find far easier to use than the newick based options (although I recognise I'm in a minority there).

Would it be possible to add the dates to the archived tree please, or could you advise on any other alternatives?

**Comment by rneher** [comment]
Hi Jerome,
sorry about the late reply. Am I understanding you correctly that you are interested in past version of the nextclade reference trees for SARS-CoV-2? This repo should contain all date-stamped releases of nextclade datasets. 

for the main builds, they are available as for example

https://nextstrain.org/ncov/gisaid/global/6m/2023-01-30

Not every day exists, because we don't get updated every day.
