### ISSUE TITLE
Request for NA reference datasets for flu subtypes

### ISSUE THREAD

**Issue by kevinlibuit** [nextstrain/nextclade_data#50]
### Context
In addition to clade typing using the HA segment, public health labs are searching for mechanisms to screen for potential variants in the NA segment associated with tamiflu resistance. With an NA reference dataset, these types of screening mechanisms could be put in play. 
### Description
Availability of a `flu_{subtype}_na` reference datasets that can be downloaded using `nextclade dataset get`.

### Examples
To analyze an H3N2 sample against an NA reference dataset, for example, one could run 
`nextclade dataset get --name="flu_h3n2_na" --reference="CY163680" --tag="2022-11-23T12:00:00Z -o h3h2_dataset` and proceed with `nextclade run --input-datset=h3h2_dataset`. Then users could parse the resulting `aa_subs` for mutations associated with tamiflu resistance.

**Comment by rneher** [comment]
Good idea! We will add a data set soon. What has been holding us back was the fact that clades are defined only for the HA gene. But we'll add NA data sets and can include tamiflu resistance mutations as 'labeled mutations'

**Comment by rneher** [comment]
we have added NA datasets for A/H3N2, A/H1N1pdm, and B/Vic!

**Comment by jrotieno** [comment]
Hi Richard, Thank you for this implementation. I haven't spotted the 'labelled mutations" column when running nextclade H1N1 NA characterization. Is this in the pipeline or I am missing something?

**Comment by ivan-aksamentov** [comment]
@jrotieno As far as I know this hasn't been done for flu datasets.

The split of mutations into labeled/unlabeled mutations requires some additional configuration in the dataset. The labels-to-mutations mapping need to be precomputed (from the existing data) and then added into `nucMutLabelMap` and `nucMutLabelMapReverse` fields of the `virus_properties.json` file of the dataset. This is how it's configured in SARS-CoV-2:

https://github.com/nextstrain/nextclade_data/blob/181a727286cf552402a833bc51aa4fee9a515492/data/datasets/sars-cov-2/references/MN908947/versions/2023-02-01T12%3A00%3A00Z/files/virus_properties.json#L3

I don't know if Richard and Cornelius plan to do this, but you can do this yourself too, by taking the existing `virus_properties.json` from a flu dataset ad adding these fields. Contributions are very welcome!

If you decide to try, in order to test things, you can override `virus_properties.json` in Nextclade CLI by using `--input-virus-properties` CLI parameter or in Nextclade Web by selecting a flu dataset, clicking "Customize dataset files" and dropping a file in the "Virus properties" section.
